### ISSUE TITLE
성준성준 프로젝트 일정 계획

### ISSUE THREAD

**Issue by smart23033** [smart23033/boostcamp_iOS_bipeople#23]
### 네비게이션
- [x] 스토리보드 뷰 만들기 (그래프, 맵은 제외)

### 캘린더 그리기
- [x] 기간 표현하기 (캘린더)

### 테이블뷰와 디테일뷰에 데이터 가져오기
  - [x] 일단 더미데이터를 만들고 직접 Realm을 사용하여 데이터가 화면에 뿌려지도록 하기(지도는 아직 제외)
  - [x] 테이블 뷰 데이터는 최근 날짜 순 정렬
  - [x] 데이터 삭제
  - [ ] 기록에 검색기능 (날짜라던지 장소라던지..)

### 통계 보여주기
  - [x] 일단 그래프 뷰를 넣어봐야 됨.
  - [x] 다음으로 위에서 만든 더미데이터를 가지고 그래프에 데이터를 표현
  - [x] 거리, 속도, 시간, 칼로리를 변경하는 필터 추가하여 항목별로 보기
  - [x] 일, 주, 월 별로 그래프 갱신
  - [x] 하단부에 누적데이터(총 주행거리, 총 주행시간, 누적 소모칼로리 등) 표기

### 지도에 경로 보여주기
  - [x] 구글 지도 넣기
  - [x] 지도에 출발점, 도착점 경로 잇기. (좌표값뭉치를 통해 폴리라인 그려야 함)
  - [x] 해당 경로에 대해 고도별 표기(Google Elevation API를 이용하여 고도별로 폴리라인의 색상 변경)
  - [x] 속도 정보를 갖고있다면 필터를 두어 고도별 / 속도별 색상변경 가능하도록 기능 추가

### 플레이스 디테일 뷰
  - [x] 해당 타입에 따라 아이콘 붙이기 + 메인에 주변 info 아이콘도
  - [x] Place Detail 뷰에 있는 테이블뷰 같은타입으로 필터링하기, 아이템 눌렀을때 Push

### 다른 파트 도와주기 및 점검
  - [ ] ARKit
  - [ ] 설정 부분?

**Comment by leejk9592** [comment]
고생하셨습니다 ㅋㅋㅋ
