### ISSUE TITLE
Gamja 프로젝트 일정 계획

### ISSUE THREAD

**Issue by leejk9592** [smart23033/boostcamp_iOS_bipeople#3]
### 0. Tutorial(~08.07)
- [x] Daum Map API Tutorial 실행해보기
- [x] T Map geoJSON 살펴보기

### 1. 네비게이션 뷰 만들기(~08.08)
 - [x] GPS permission alert(금방)
 - [x] 구글맵을 처음에 띄우고, 중심에는 현 위치가 있다(4시간)
 - [x] 네비게이션 바에는 검색 바와 비활성화된 출발 버튼(4시간)

### 2. 장소를 검색으로 결정하는 방법 제공(~08.09)
 - [x] 검색창을 클릭해 활성화, 입력이 될  때마다 `Google Place API`를 통해 테이블 뷰 갱신(6시간)
 - [x] 장소가 결정 되면 출발 버튼을 활성화(2시간)

### 3. 장소를 맵을 터치한 위치로 결정하는 방법 제공(~08.10)
 - [x] 터치한 위치의 위도/경도를 `Google Place API`로 요청해, 터치된 지점이 맵 중앙이 되고 응답 결과인 지명을 이용해 마커를 생성한다. (6시간)
 - [x] 장소가 결정 되면 출발 버튼을 활성화(2시간)

### 4. 출발 버튼을 눌러 네비게이션을 실행(~08.12)
- [x] 출발지와 도착지의 위도/경도를 T Map API로 요청해 경로 응답을 받아, `index`, `좌표`, `description`, `name(경유지)`를 객체로 변환한다. (12시간)
- [x] 구글 맵에 `polyline`을 이용해 index 순으로 선분을 이어준다.(4시간)

### 5. 위치 데이터 기록(~08.13)
- [x] 네비게이션 작동 후 부터 끝날 때까지, 위치가 변할 때마다 (위도/경도/타임스탬프) 튜플을 배열에 추가(8시간)

### 6. 도착 처리(~08.14)
- [x] 먼저 축적한 데이터를 저장한 후, Alert 창에 (주행거리, 주행시간, 평균속도, 소모칼로리)를 계산해 표시. 확인을 누르면 사라지면서 네비게이션을 초기화.(8시간)

### 7. 주행 기록 도중에 확인을 누른 경우(~08.15)
- [x] `정말 저장하고 그만 두시겠습니까?`라는 Alert 창을 띄운 후,  확인을 누르면 `도착 처리`, 취소를 누르면 네비게이션을 계속 진행(8시간)

### 8. 주행 기록 도중에 취소를 누른 경우(~08.16)
- [x] `정말 취소하고 그만 두시겠습니까?`라는 Alert 창을 띄운 후, 확인이 눌리면 네비게이션을 초기화, 취소를 누르면 네비게이션을 계속 진행(4시간)

### 9. 경로이탈 처리(~08.18)
- [x] 현재 속한 경로의 직선에서 법선을 그어 일정 거리 이상으로 멀어지면, Alert 창에 `경로이탈 경고` 문구를 띄운 후, 타이머가 5초가 지나면 강제로 현재 위치에서 도착지 까지 새 경로를 받아옴,
(20시간)

### 11. 꾸미기(~08.24)
- [x] 음성 안내
- [x] 파트별 합치기 + UI 꾸미기
- [ ] 밤이 되면 배경 어두운 색

**Comment by Sikurity** [comment]
# 1. 네비게이션 뷰 만들기
 - [ ] GPS permission alert(금방)
 - [ ] 구글맵을 처음에 띄우고, 중심에는 현 위치가 있다(4시간)
 - [ ] 네비게이션 바에는 서치바와 비활성화된 출발 버튼(4시간)

## ~1일

# 2. 장소를 검색으로 결정하는 방법 제공
 - [ ] 검색창을 클릭해 활성화, 입력이 될  때마다 `구글 플레이스 API`를 통해 테이블 뷰 갱신(6시간)
 - [ ] 장소가 결정 되면 출발 버튼을 활성화(2시간)

## ~2일

# 3. 장소를 맵을 터치한 위치로 결정
 - [ ] 터치한 위치의 위도/경도를 T map API로 요청해, 터치된 지점이 맵 중앙이 되고 응답 결과인 지명을 이용해 마커가 생성한다. (6시간)
 - [ ] 장소가 결정 되면 출발 버튼을 활성화(2시간)

## ~3일

# 2. 출발 버튼을 눌러 네비게이션을 실행
- [ ] 출발지와 도착지의 위도/경도를 T Map API로 요청해 경로 응답을 받아, `index`, `좌표`, `description`, `name(경유지)`를 객체로 변환한다. (12시간)
- [ ] 구글 맵에 `polyline`을 이용해 index 순으로 선분을 이어준다.(4시간)

## ~5일 (2일치)

# 3. 네비게이션이 작동 된 후부터. 위치가 변할 때마다 (위도/경도/타임스탬프)를  튜플 배열에 추가(8시간)

## ~6일

# 4. 도착 처리
- [ ] 먼저 축적한 데이터를 저장한 후, Alert 창에 (주행거리, 주행시간, 평균속도, 소모칼로리)를 계산해 표시. 확인을 누르면 사라지면서 네비게이션을 초기화.(8시간)

## ~7일

# 5. 경로 중간에 확인을 누른 경우
- [ ] `정말 저장하고 그만두시겠습니까?`라는 Alert 창을 띄운 후,  확인을 누르면 `도착 처리`, 취소를 누르면 네비게이션을 계속 진행(8시간)

## ~8일

# 6. 중간에 취소를 누른경우
- [ ] `정말 그만 두시겠습니까?`라는 Alert 창을 띄운 후, 확인이 눌리면 네비게이션을 초기화, 취소를 누르면 네비게이션을 계속 진행(4시간)

## ~8.5일

# 7. 경로이탈 처리
- [ ] 현재 속한 경로의 직선에서 법선을 그어 일정 거리 이상으로 멀어지면, Alert 창에 `경로이탈 경고` 문구를 띄운 후, 타이머가 5초가 지나면 강제로 현재 위치에서 도착지 까지 새 경로를 받아옴,
(12시간)

## ~10일

# 8. 테스트 및 버그해결(4일치)

## ~14일 

# 9. 꾸미기(2일치)
- [ ] SiriKit을 이용한 음성 안내 도전
- [ ] 파트별 합치기 + UI 꾸미기
- [ ] 밤이 되면 배경 어두운 색

## ~16일

**Comment by leejk9592** [comment]
Reopen For The Tutor

**Comment by leejk9592** [comment]
ㅠㅠ
